env:
  commonjs: true
  es2020: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  load: readonly
  BigInt: readonly
parserOptions:
  ecmaVersion: 2020
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
  no-extra-parens:
    - warn
    - all
  array-callback-return:
    - warn
  prefer-spread:
    - warn
  no-useless-constructor:
    - warn
  no-console:
    - off
  arrow-parens:
    - error
    - as-needed
  no-multi-spaces:
    - error
