name: Code Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  compile:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*, latest]

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: package-lock.json
    - run: npm i
    - run: npm run test
