name: Prerelease

on:
  push:
    branches:
      - "master"
      - "v[0-9]+"
    tags:
      - "!**"
  pull_request:

env:
  LEFTHOOK: "0"
  HUSKY: "0"

jobs:
  publish:
    name: Publish Prerelease
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v6

      - name: Use Node LTS
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish to pkg.pr.new
        run: pnpm dlx pkg-pr-new publish
