name: Publish TypeDoc

on:
  push:
    branches:
      - master

env:
  LEFTHOOK: "0"
  HUSKY: "0"

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build docs
        run: pnpm run build:docs

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/

  deploy-docs:
    needs: build-docs

    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
